examples/README.md

As of now, the examples directory only contains the `traceresponse` example, so updated accordingly.

Cleanup examples README.md

---

opentelemetry-datadog/src/exporter/model/v05.rs

This pull request introduces part of  [Datadog Source Code Integration](https://docs.datadoghq.com/integrations/guide/source-code-integration/?tab=go)
Added compile time env variables: `DD_GIT_REPOSITORY_URL` and `DD_GIT_COMMIT_SHA`. Exporter will send this information in sampled traces.
```
DD_GIT_REPOSITORY_URL="git@github.com:Hartigan/opentelemetry-rust-contrib.git" DD_GIT_COMMIT_SHA="e4b2b10970d10237457a3d1a87a3e75cf41488ad" cargo build
```

Datadog Source Code Integration

---

opentelemetry-stackdriver/CHANGELOG.md
opentelemetry-stackdriver/Cargo.toml
opentelemetry-stackdriver/README.md
opentelemetry-stackdriver/src/google_trace_context_propagator.rs
opentelemetry-stackdriver/src/lib.rs

Issue https://github.com/open-telemetry/opentelemetry-rust-contrib/issues/3
Added `GoogleTraceContextPropagator` to `opentelemetry-stackdriver` crate, behind a feature flag `propagator`.
Implementation is based on the [official GCP golang library implementation](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/main/propagator/propagator.go) and Rust `opentelemetry` [implementation of W3C Propagator](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/src/propagation/text_map_propagator.rs).

Stackdriver - adding support for Google X-Cloud-Trace-Context propagation format

---

opentelemetry-contrib/CHANGELOG.md
opentelemetry-contrib/src/trace/propagator/binary/base64_format.rs
opentelemetry-contrib/src/trace/propagator/binary/binary_propagator.rs

Fixes #31 
Updates `deserialize_from_bytes` to take a byte slice instead of an owned vec.

Make binary propagator take byte slice instead of vec

---

opentelemetry-user-events-metrics/CHANGELOG.md
opentelemetry-user-events-metrics/Cargo.toml
opentelemetry-user-events-metrics/examples/basic.rs

UserEvent Metric Exporter release 0.2.2

---

opentelemetry-user-events-metrics/CHANGELOG.md
opentelemetry-user-events-metrics/Cargo.toml

Prepare changelog and version to release user_events metrics exporter.
I think there should be a release done for all other crates as well.

Prepare for release user_events_metrics exporter 0.3.0

---

opentelemetry-stackdriver/Cargo.toml
opentelemetry-stackdriver/src/google_trace_context_propagator.rs

Simplify parsing trace context to avoid the complexity of regular expressions (and the added dependency).
Follow-up for #25.

stackdriver: parse trace context without regex

---

opentelemetry-stackdriver/CHANGELOG.md
opentelemetry-stackdriver/Cargo.toml
opentelemetry-stackdriver/src/lib.rs

#50 regressed the support for actually using the `GcpAuthorizer`: it used the `dep:gcp_auth` syntax for enabling the dependency by default, but the actual `GcpAuthorizer` code was guarded by a `gcp_auth` **feature** which didn't exist anymore. Bring back a named feature for this (now called `gcp-authorizer` to match `yup-authorizer`).
This time I will start a PR for my work repository based on my branch to make sure it actually works.

stackdriver: fix Cargo features for GcpAuthorizer

---

opentelemetry-datadog/Cargo.toml
opentelemetry-datadog/benches/datadog_exporter.rs

Added benchmark for DatadogExporter with generated HTTP spans and some custom attributes

Add benchmark for DatadogExporter

---

opentelemetry-etw-logs/src/logs/converters.rs
opentelemetry-stackdriver/CHANGELOG.md
opentelemetry-stackdriver/Cargo.toml

Fixes: 
- https://github.com/open-telemetry/opentelemetry-rust-contrib/pull/57#issuecomment-2015740499
- Clippy: useless vector
Bump corresponding crates.

chore(deps): bump yup-oauth2 and hyper-rustls version

---

opentelemetry-resource-detectors/CHANGELOG.md
opentelemetry-resource-detectors/Cargo.toml
opentelemetry-resource-detectors/README.md
opentelemetry-resource-detectors/src/host.rs
opentelemetry-resource-detectors/src/lib.rs

Add the Host Resource detector retrieving the "host.id" as defined in: https://opentelemetry.io/docs/specs/semconv/resource/host/
Defined in #56 
Co-authored-by: rogercoll <rogercoll@users.noreply.github.com>

feat: Add host.id resource detector

---

opentelemetry-resource-detectors/CHANGELOG.md
opentelemetry-resource-detectors/README.md
opentelemetry-resource-detectors/src/host.rs

Adds the "host.arch" resource attribute to the Host detector.

feat: add host.arch resource attribute

---

Cargo.toml
scripts/test.sh

Excluding crates failing to build in the current pipeline. This may be due to the rust toolchain upgrade, or the dependency upgrades. These can be incrementally brought back once they are fixed.
Refer #64 for some of the errors tried fixing, but there are somewhat more.

Exclude crates failing to build

---

opentelemetry-user-events-logs/CHANGELOG.md
opentelemetry-user-events-logs/Cargo.toml
opentelemetry-user-events-metrics/CHANGELOG.md
opentelemetry-user-events-metrics/Cargo.toml

- user_events Metrics and Logs exporter.
- update the version to v0.4.0 for user_events logs and metrics exporters.
- Updated changelog.

user_events exporters: Prepare for v0.4.0 release

---

Cargo.toml
opentelemetry-datadog/Cargo.toml
opentelemetry-datadog/benches/datadog_exporter.rs
opentelemetry-datadog/src/exporter/mod.rs
opentelemetry-datadog/src/exporter/model/mod.rs
opentelemetry-datadog/src/lib.rs
opentelemetry-zpages/Cargo.toml
opentelemetry-zpages/src/trace/aggregator.rs
opentelemetry-zpages/src/trace/span_queue.rs

Fix some deprecated api calls and clippy reports

---

opentelemetry-aws/Cargo.toml
opentelemetry-contrib/Cargo.toml
opentelemetry-datadog/Cargo.toml
opentelemetry-resource-detectors/Cargo.toml
opentelemetry-zpages/Cargo.toml
scripts/lint.sh
scripts/test.sh

- opentelemetry-aws
- opentelemetry-contrib
- opentelemetry-datadog
- opentelemetry-resource-detectors
- opentelemetry-zpages
Re-enable testing for opentelemetry-datadog, except surf-client
Fixes #

Prepare for relate (most) contrib crates.

---

opentelemetry-zpages/Cargo.toml

opentelemetry-zpages publishin fails with error:
```
Uploading opentelemetry-zpages v0.9.0 (/home/labhas/obs/ot/lalit/rust/opentelemetry-rust-contrib/opentelemetry-zpages)
error: failed to publish to registry at https://crates.io
Caused by:
the remote server responded with an error (status 400 Bad Request): The following category slugs are not currently supported on crates.io: experimental
See https://crates.io/category_slugs for a list of supported slugs.`
```
Removing unsupported experimental category flag in this PR.

opentelemetry-zpages publish fix - remove unsupported `experimental` category slug

---

opentelemetry-stackdriver/CHANGELOG.md
opentelemetry-stackdriver/Cargo.toml
opentelemetry-stackdriver/src/lib.rs
opentelemetry-stackdriver/src/proto/api.rs
opentelemetry-stackdriver/src/proto/devtools/cloudtrace/v2.rs
opentelemetry-stackdriver/src/proto/logging/v2.rs

* Remove `yup-authorizer` feature, which I suspect is unused and depends on yup-oauth2 which doesn't seem to get much maintenance
* Update all the dependencies:
* http, reqwest
* prost, tonic, tonic-build
* opentelemetry-*

stackdriver: prepare for release

---

opentelemetry-datadog/CHANGELOG.md
opentelemetry-datadog/Cargo.toml
opentelemetry-datadog/benches/datadog_exporter.rs
opentelemetry-datadog/examples/agent_sampling.rs
opentelemetry-datadog/src/exporter/mod.rs
opentelemetry-datadog/src/exporter/model/mod.rs
opentelemetry-datadog/src/exporter/model/v03.rs
opentelemetry-datadog/src/exporter/model/v05.rs
opentelemetry-datadog/src/lib.rs
opentelemetry-etw-logs/src/logs/exporter.rs
opentelemetry-resource-detectors/src/process.rs
opentelemetry-stackdriver/src/lib.rs
opentelemetry-stackdriver/src/proto/api.rs
opentelemetry-user-events-logs/src/logs/exporter.rs

Upgrade otel and hyper dependencies, change HttpClient example to hyper over unix socket.
I removed writing the resource for every span, as the field was [removed from `SpanData`](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/CHANGELOG.md?plain=1#L58).

Upgrade hyper and otel dependencies

---

opentelemetry-stackdriver/src/proto/devtools/cloudtrace/v2.rs
opentelemetry-stackdriver/src/proto/logging/v2.rs

`Send` and `Sync` in code generated by tonic 0.12.2 is fully qualified as `std::marker::Send` and `std::marker::Sync`.
Refreshes generated code in opentelemetry-stackdriver to fix "generated_code_is_fresh" test.

Refresh generated code in opentelemetry-stackdriver

---

opentelemetry-stackdriver/src/lib.rs

Fixes #95 
When upgrading to tonic 0.12, tonic stopped implicitly setting up tls roots even when the features are enabled for it. This PR makes this setup explicit in stackdriver.
It doesn't change user-facing API  and the change is relatively trivial. I manually tested this in my repo and the error went away. I don't think there is a good way to unit test this unless we want the unit tests to verify connectivity to gcp servers.

Adding explicit tls roots configuration to stackdriver

---

opentelemetry-stackdriver/CHANGELOG.md
opentelemetry-stackdriver/src/lib.rs

Fixes #100 
Adds `MonitoredResource::CloudRunJob` which adds the appropriate labels for the `cloud_run_job` monitored resource type.

Add cloud_run_job to MonitoredResource

---

opentelemetry-stackdriver/proto/google/api/annotations.proto
opentelemetry-stackdriver/proto/google/api/client.proto
opentelemetry-stackdriver/proto/google/api/field_behavior.proto
opentelemetry-stackdriver/proto/google/api/http.proto
opentelemetry-stackdriver/proto/google/api/label.proto
opentelemetry-stackdriver/proto/google/api/launch_stage.proto
opentelemetry-stackdriver/proto/google/api/monitored_resource.proto
opentelemetry-stackdriver/proto/google/api/resource.proto
opentelemetry-stackdriver/proto/google/devtools/cloudtrace/v2/trace.proto
opentelemetry-stackdriver/proto/google/devtools/cloudtrace/v2/tracing.proto
opentelemetry-stackdriver/proto/google/logging/type/http_request.proto
opentelemetry-stackdriver/proto/google/logging/type/log_severity.proto
opentelemetry-stackdriver/proto/google/logging/v2/log_entry.proto
opentelemetry-stackdriver/proto/google/logging/v2/logging.proto
opentelemetry-stackdriver/proto/google/logging/v2/logging_config.proto
opentelemetry-stackdriver/proto/google/rpc/status.proto
opentelemetry-stackdriver/src/proto/api.rs

https://github.com/open-telemetry/opentelemetry-rust-contrib/pull/102 updated proto files, but they've diverged again.
Probably these should remain `#[ignore]`d. Maybe run a separate (scheduled?) build check for them?

Regenerate proto files in opentelemetry-stackdriver.

---

opentelemetry-datadog/Cargo.toml
opentelemetry-datadog/examples/agent_sampling.rs
opentelemetry-datadog/examples/datadog.rs

Fixes #118
- updated Datadog to use OTel 0.26
- changed version management of OTel dependencies to workspace

chore: update Datadog to otel 0.26

---

.github/workflows/ci.yml
opentelemetry-datadog/Cargo.toml
opentelemetry-user-events-logs/Cargo.toml

- removed unused dependencies
- added cargo machete job to CI to make sure no unused dependencies are left over
- also updated `actions/checkout` GHA to the latest version `v4`

chore: add cargo machete and remove unused dependencies

---

opentelemetry-resource-detectors/src/k8s.rs
opentelemetry-resource-detectors/src/k8stest.rs

Fixes #48 
This PR adds a Kubernetes (k8s) ResourceDetector for OpenTelemetry Rust contrib. The detector extracts Kubernetes-specific resource attributes (Pod name, Namespace, and Node name) from environment variables and adds them as OpenTelemetry resource attributes.
**New K8sResourceDetector:**
- Detects and retrieves the following k8s environment variables:
- K8S_POD_NAME: The name of the Kubernetes pod.
- K8S_NAMESPACE_NAME: The name of the Kubernetes namespace.
- K8S_NODE_NAME: The name of the node where the pod is running.
- Fallback to default values (e.g., "unknown_pod") if these environment variables are not set.
**Integration with Resource Chain:**
The K8sResourceDetector is added to the list of detectors when creating resources, ensuring Kubernetes-specific attributes are …

Added k8s ResourceDetector

---

opentelemetry-datadog/CHANGELOG.md
opentelemetry-datadog/Cargo.toml

- prepare Datadog 0.14 release

prepare Datadog 0.14 release

---

opentelemetry-etw-metrics/CHANGELOG.md
opentelemetry-etw-metrics/Cargo.toml
opentelemetry-etw-metrics/examples/basic.rs
opentelemetry-etw-metrics/src/etw/mod.rs
opentelemetry-etw-metrics/src/exporter/mod.rs

Updating just the package, and minimal changes to make it work with new. Internal logging needs to be revisited before release.

Update Metric-Etw exporter to use 0.27 of api and sdk

---

opentelemetry-user-events-metrics/CHANGELOG.md
opentelemetry-user-events-metrics/Cargo.toml
opentelemetry-user-events-metrics/examples/basic-metrics.rs
opentelemetry-user-events-metrics/src/exporter/mod.rs
opentelemetry-user-events-metrics/src/tracepoint/mod.rs

Update user_events metrics exporter to otel 0.27, add internal logs

---

opentelemetry-user-events-logs/CHANGELOG.md
opentelemetry-user-events-logs/Cargo.toml
opentelemetry-user-events-logs/src/logs/exporter.rs
opentelemetry-user-events-logs/src/logs/reentrant_logprocessor.rs
scripts/lint.sh

A small change to enable event_enabled for opentelemetry-user-events-logs example code

Enable event_enabled flag for opentelemetry-user-events-logs example code

---

opentelemetry-contrib/benches/new_span.rs
opentelemetry-contrib/src/trace/context.rs
opentelemetry-contrib/src/trace/tracer_source.rs
opentelemetry-datadog/examples/agent_sampling.rs
opentelemetry-datadog/src/exporter/intern.rs
opentelemetry-datadog/src/exporter/mod.rs
opentelemetry-datadog/src/exporter/model/unified_tags.rs

See related issue: open-telemetry/opentelemetry-rust#2370
Fixed the following lint errors:
```sh
error: use of deprecated method `opentelemetry_sdk::trace::Builder::with_config`: Config is becoming a private type. Use Builder::with_{config_name}(resource) instead. ex: Builder::with_resource(resource)
```
```sh
error: the following explicit lifetimes could be elided: 'a
```
```sh
error: empty line after doc comment
```

Fix CI lint errors from new stable toolchain v1.83

---

Cargo.toml
stress/Cargo.toml
stress/src/throughput.rs
stress/src/user_events_enabled.rs

I believe it would be benefitial to have stress framework copied from main to the contrib repo, to enable packages from this repo do necessary tests.
Have added the framework, along with the sample stress test for user-events enabled. The stress test result for user_events can be discussed separately in #133.
Ps. - It would be difficult to keep stress framework in sync between the two repos. I don't see any other easy way as of now, unless we publish the framework as a separate crate. But this would incur added responsibility in maintaining it.

Add stress-test framework to contrib repo.

---

opentelemetry-aws/src/detector/lambda.rs

Add `aws.log.group.names` resource attribute to `LambdaResourceDetector` using the `AWS_LAMBDA_LOG_GROUP_NAME` environment variable that is [always available in Lambda runtimes](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-runtime).
This follows the OpenTelemetry semantic convention for [AWS Logs attributes](https://opentelemetry.io/docs/specs/semconv/attributes-registry/aws/#amazon-logs-attributes).
The semantic convention specifies that `aws.log.group.names` should be an array of strings to support cases like multi-container applications, though in AWS Lambda we'll only ever have a single log group.

feat: add `aws.log.group.names` attribute to `LambdaResourceDetector`

---

stress/Cargo.toml
stress/src/user_events.rs

Adding test for user-events exporter, with steps to take results by enabling and disabling user-events. Also, added the initial results I got in my devenv. This mayn't be accurate. The next steps are to evaluate the results, and see potential improvements required.

Add stress test for user-events logs exporter

---

opentelemetry-resource-detectors/src/host.rs

On Linux `/etc/machine-id` has a newline, it's unusual to have newlines in a resource value like `host.id`, so this change trims the whitespace around the value.
* [N/A] Unit tests added/updated (if applicable)
* [N/A] Appropriate `CHANGELOG.md` files updated for non-trivial, user-facing changes
* [N/A] Changes in public API reviewed (if applicable)

Trim host-id whitespace on Linux

---

opentelemetry-user-events-logs/src/logs/exporter.rs
stress/src/user_events.rs

The `Arc` is not required for eventheader-provider, so removing it. This has significant perf improvements as updated in the results.
Before (refer: #142)
is_enabled:true:
1 thread: 30,866,752 iterations/sec
16 threads: 16,915,860 iterations/sec
After:
is_enabled:false
1 thread: 41,555,620 iterations/sec
16 threads: 20,119,895 iterations/sec

[user_events logs] Remove Arc reference from eventheader provider

---

opentelemetry-datadog/src/exporter/mod.rs

Stable sort is not required for grouping, while unstable gives slightly better performance according to `opentelemetry-datadog/benches/datadog_exporter.rs`
Changed sort implementation to perform grouping by trace_id to use unstable sort (not preserving order of already sorted items). It has slightly better performance that stable sort while not violating [contract](https://github.com/DataDog/datadog-agent/blob/c076ea9a1ffbde4c76d35343dbc32aecbbf99cb9/pkg/trace/api/version.go#L30) of DD api.
Before:
<details>
<summary>before</summary>
```
Benchmarking export 128 traces with 4 spans: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 5.9s, enable flat sampling, or reduce sample count to 60.
export 128 traces with 4 spans
time: …
```

Use unstable sort to group traces in DD exporter.

---

opentelemetry-stackdriver/CHANGELOG.md
opentelemetry-stackdriver/Cargo.toml

Fixes #147
opentelemetry-stackdriver does not need the server implementation from tonic, which brings in axum etc. This change brings in all features other than that, which are needed for the client implementation.

Remove server feature from tonic in opentelemetry-stackdriver

---

.github/workflows/ci.yml
README.md
opentelemetry-aws/Cargo.toml
opentelemetry-contrib/Cargo.toml
opentelemetry-datadog/Cargo.toml
opentelemetry-etw-logs/Cargo.toml
opentelemetry-resource-detectors/Cargo.toml
opentelemetry-stackdriver/Cargo.toml
opentelemetry-user-events-logs/Cargo.toml
opentelemetry-zpages/Cargo.toml
scripts/msrv.sh
scripts/msrv_config.json
scripts/patch_dependencies.sh

- Most of the MSRVs were not adjusted with the recent update to OTel 0.27 version (fixed that)
- Also added back the MSRV CI job and migrated to a very similar approach like `opentelemetry-rust`, just using `cargo-msrv` instead to verify it
- I had to set `1.71.1` in the CI job for all the packages, because `cargo-msrv` doesn't work with Rust <1.71 (also added a comment in the config file), but that doesn't matter much since the next OTel version will raise the MSRV to 1.75 anyway
- Also had to patch two dependencies otherwise it wouldn't work for that specific version

Add back MSRV CI job and adjust MSRVs

---

opentelemetry-stackdriver/src/lib.rs

Fixes #
While preparing for a new `opentelemtry-stackdriver` release and updating the dependencies it seems a bug was introduced.
The new API stores resource attributes directly in the exporter. By adding this two instances of `RwLock<Resource>` were introduced, making it impossible to set the resource (using `set_resource`) as the `ExporterContext` uses a different pointer.
This fixes the issue and also updates resource attribute key mappings to the latest version (added k8s mappings and removed outdated service.name mapping).

Fix stackdriver resources

---

opentelemetry-datadog/CHANGELOG.md
opentelemetry-datadog/Cargo.toml
opentelemetry-stackdriver/CHANGELOG.md
opentelemetry-stackdriver/Cargo.toml

Fixes #
- no relevant breaking changes in `thiserror` v2

Bump thiserror to v2

---

opentelemetry-aws/Cargo.toml
opentelemetry-aws/src/trace/xray_propagator.rs
opentelemetry-contrib/Cargo.toml
opentelemetry-contrib/src/trace/propagator/trace_context_response.rs
opentelemetry-contrib/src/trace/tracer_source.rs
opentelemetry-datadog/Cargo.toml
opentelemetry-datadog/src/lib.rs
opentelemetry-stackdriver/Cargo.toml
opentelemetry-stackdriver/src/google_trace_context_propagator.rs

- Since the MSRV will become 1.70+ via #150 there is no need for `once_cell` anymore
- The implementation is identical to the OTel one
https://github.com/open-telemetry/opentelemetry-rust/blob/b53c19e2e6c4f8f18d2427c40556b2d0b574aa50/opentelemetry-sdk/src/propagation/trace_context.rs#L18-L23
-  I also renamed the header fields static to `TRACE_CONTEXT_HEADER_FIELDS` to keep identical through out the different packages (they are not public so no harm here)
Do you want me to add it to the changelog or not worth it? No user-facing changes 🙂

Replace once_cell with OnceLock

---

opentelemetry-datadog/CHANGELOG.md
opentelemetry-datadog/examples/agent_sampling.rs
opentelemetry-datadog/examples/datadog.rs
opentelemetry-datadog/src/exporter/mod.rs
opentelemetry-datadog/src/lib.rs

- Relates to open-telemetry/opentelemetry-rust#2369
- I implemented it identical to the Zipkin Exporter

Replace global::shutdown_tracer_provider with tracer_provider.shutdown()

---

opentelemetry-datadog/src/lib.rs

Fixes #
The name of the crate in the batched/performance example is incorrect -- it should be `opentelemetry_sdk`, not `opentelemetry`.

docs(datadog): Correct an erroneous reference to the opentelemetry_sdk crate

---

examples/traceresponse/src/client.rs
examples/traceresponse/src/server.rs
opentelemetry-contrib/CHANGELOG.md
opentelemetry-contrib/Cargo.toml
opentelemetry-contrib/src/trace/exporter/jaeger_json.rs
opentelemetry-datadog/CHANGELOG.md
opentelemetry-datadog/examples/agent_sampling.rs
opentelemetry-datadog/examples/datadog.rs
opentelemetry-datadog/src/exporter/mod.rs
opentelemetry-datadog/src/exporter/model/mod.rs
opentelemetry-datadog/src/lib.rs

- Follow-up to https://github.com/open-telemetry/opentelemetry-rust-contrib/pull/155/files/1f8b9f034b76adec7a69a30c3afc91b7f2d3e449#r1924545070
- Also adjusted all the examples I could find

Remove global set_tracer_provider from trace pipelines

---

opentelemetry-user-events-metrics/local-setup/README.md
opentelemetry-user-events-metrics/local-setup/cloud-init.yaml

Note: I found this setup helpful for testing my latest `user_events` metrics PR, so thought of adding it. Feel free to reject the PR if this doesn't seem helpful :)
Setting up the Linux kernel with user_events enabled can be challenging, especially since the latest WSL images do not *yet* support it. An easier alternative is to use an Ubuntu 24.04 (or greater) VM, which can be run on Hyper-V, VirtualBox, or other virtualization platforms.
This PR introduces a cloud-init.yaml configuration file for creating an Ubuntu VM using [multipass](https://multipass.run/), with user_events support and other required configurations for decoding `proto` packets. This setup is cross-platform, allowing developers to run it on Windows, macOS, or Linux, simplifying the environment setup process for …

Add Multipass Setup for user_events metrics testing on Ubuntu 24.04 VM

---

opentelemetry-datadog/README.md
opentelemetry-resource-detectors/README.md

- added myself as owner for Datadog + Resource Detectors (relates to #163)
- also added the missing badges to the Resource Detectors readme

add owner to readme

---

Cargo.toml
examples/traceresponse/Cargo.toml
opentelemetry-aws/Cargo.toml
opentelemetry-contrib/Cargo.toml
opentelemetry-datadog/Cargo.toml
opentelemetry-etw-logs/Cargo.toml
opentelemetry-etw-metrics/Cargo.toml
opentelemetry-resource-detectors/Cargo.toml
opentelemetry-stackdriver/Cargo.toml
opentelemetry-user-events-logs/Cargo.toml
opentelemetry-user-events-metrics/Cargo.toml
opentelemetry-zpages/Cargo.toml
scripts/lint.sh
stress/Cargo.toml

- similar to open-telemetry/opentelemetry-rust#2674

use workspace lint configuration

---

opentelemetry-contrib/Cargo.toml
opentelemetry-contrib/src/trace/exporter/jaeger_json.rs
opentelemetry-etw-metrics/src/etw/mod.rs
opentelemetry-resource-detectors/src/host.rs
opentelemetry-stackdriver/Cargo.toml
opentelemetry-stackdriver/src/lib.rs

- there are still some more `async-trait` usages, but they have to wait till the next OTel SDK release

leverage native async trait in JaegerJsonRuntime and GcpAuthorizer

---

opentelemetry-user-events-logs/src/logs/exporter.rs

- Avoid string allocation when exporting log record attributes

[opentelemetry-user-events-logs] Avoid string allocation when exporting log record attributes

---

opentelemetry-user-events-logs/src/logs/exporter.rs

- Use `pub(crate)` instead of `pub` for internal types for better readability
- Use `const fn` for `get_severity_level`

[opentlemetry-user-events-logs] Minor refactoring

---

Cargo.toml
opentelemetry-aws/Cargo.toml
opentelemetry-aws/src/detector/lambda.rs
opentelemetry-datadog/Cargo.toml
opentelemetry-datadog/src/exporter/model/unified_tags.rs
opentelemetry-user-events-metrics/src/tracepoint/mod.rs
stress/src/throughput.rs

- similar to open-telemetry/opentelemetry-rust#2728

chore: enable Rust 2024 edition lints

---

opentelemetry-stackdriver/CHANGELOG.md
opentelemetry-stackdriver/src/lib.rs

This adds 4 more monitored resources to bring this on par with the official node and go SDKs.
* gae_app (`MonitoredResource::AppEngine`) https://cloud.google.com/logging/docs/api/v2/resource-list#tag_gae_app
* gce_instance (`MonitoredResource::ComputeEngine`) https://cloud.google.com/logging/docs/api/v2/resource-list#tag_gce_instance
* cloud_function (`MonitoredResource::CloudFunction`) https://cloud.google.com/logging/docs/api/v2/resource-list#tag_cloud_function
* k8s_container (`MonitoredResource::KubernetesEngine`) https://cloud.google.com/logging/docs/api/v2/resource-list#tag_k8s_container

feat: stackdriver: Bring monitored resources on par with official SDKs

---

.github/workflows/ci.yml

- equivalent to open-telemetry/opentelemetry-rust#1655

ci: replace actions-rs GHA

---

Cargo.toml
actix-web-opentelemetry/CHANGELOG.md
actix-web-opentelemetry/Cargo.toml
actix-web-opentelemetry/src/client.rs
actix-web-opentelemetry/src/middleware/metrics.rs
actix-web-opentelemetry/src/util.rs
opentelemetry-contrib/Cargo.toml

Hi! Moving this PR to this repo. I notice that your current PR to upgrade to 0.29 is still in progress. I can fix the conflicts in this PR after that one is merged in. If you were planning on upgrading this crate yourself, you can feel free to close this PR.
Initial PR: https://github.com/OutThereLabs/actix-web-opentelemetry/pull/192

chore: Upgrade actix-web-opentelemetry to 0.29

---

.github/workflows/ci.yml
deny.toml

@cijothomas this should fix your deny problem and then you can merge this change into your PR and remove the ignored CVE

chore: exclude protobuf from cargo deny and fix config issues

---

opentelemetry-aws/CHANGELOG.md
opentelemetry-aws/Cargo.toml
opentelemetry-aws/src/trace/id_generator.rs
opentelemetry-aws/src/trace/xray_propagator.rs

Fixes # (no specific issue)
Design discussion issue (if applicable) # (not applicable)
Updates the OpenTelemetry AWS crate to use the latest 0.29.0 version of OpenTelemetry.
Changes include:
- Updated imports for `TraceError` which moved from `opentelemetry::trace::TraceError` to `opentelemetry_sdk::trace::TraceError`
- Fixed issue with moved value in error handling for `TraceStateError`
- Updated XrayIdGenerator doctest to use the new API for configuring the IdGenerator

chore(aws): update OpenTelemetry dependencies to 0.29.0

---

opentelemetry-user-events-logs/CHANGELOG.md
opentelemetry-user-events-logs/src/logs/exporter.rs
opentelemetry-user-events-logs/src/logs/reentrant_logprocessor.rs

1. Handle shutdown to exporter
2. No more internal logs - This limits self observability, but can add some metric, or eprintln() in the future, if this turns out to be an issue.

fix: Make usereventlogexporter re-entrant safe and handle shutdown

---

opentelemetry-etw-logs/CHANGELOG.md
opentelemetry-etw-logs/src/logs/exporter/mod.rs
opentelemetry-etw-logs/src/logs/exporter/part_b.rs
opentelemetry-etw-logs/src/logs/reentrant_logprocessor.rs
opentelemetry-user-events-logs/src/logs/exporter.rs

Now that 0.29 upstream is added, shutdown can be performed by unregistering the provider.
Nit cleanup on export() method.
Rename "Logs" to "Log" for partB name, consistent with user-events exporter.

fix: ETW LogExporter to unregister on shutdown

---

opentelemetry-stackdriver/CHANGELOG.md
opentelemetry-stackdriver/Cargo.toml
opentelemetry-stackdriver/src/lib.rs

Fixes #
Updates to open-telemetry 0.29
Notes:
The mpsc channel is backed by `Arc`s thus no additional interior mutability is needed.
I dropped the error wrapping in the internal-log only otel_error! macro usage. The macro now places the expr in multiple places; thus, it cannot move a value anymore. The name has enough information about the error kind. The display impl of the TraceError and Error variants did not add any additional context. Also, this is for internal debugging only.

chore: update stackdriver's OpenTelemetry to 0.29

---

opentelemetry-user-events-logs/src/logs/exporter.rs

Handle scenario where event_name is empty string.
```rust
error!(name: "", target: "my-system", event_id = 20, user_name = "otel", user_email = "otel@opentelemetry.io", message = "This is an example message");)
```

fix: user_events log: Handle empty event_name

---

opentelemetry-aws/CHANGELOG.md
opentelemetry-contrib/CHANGELOG.md
opentelemetry-contrib/Cargo.toml
opentelemetry-datadog/CHANGELOG.md
opentelemetry-datadog/Cargo.toml
opentelemetry-etw-logs/CHANGELOG.md
opentelemetry-etw-logs/Cargo.toml
opentelemetry-etw-metrics/CHANGELOG.md
opentelemetry-etw-metrics/Cargo.toml
opentelemetry-resource-detectors/CHANGELOG.md
opentelemetry-resource-detectors/Cargo.toml
opentelemetry-stackdriver/CHANGELOG.md
opentelemetry-stackdriver/Cargo.toml
opentelemetry-user-events-logs/CHANGELOG.md
opentelemetry-user-events-logs/Cargo.toml
opentelemetry-user-events-metrics/CHANGELOG.md
opentelemetry-user-events-metrics/Cargo.toml
opentelemetry-user-events-trace/CHANGELOG.md
opentelemetry-user-events-trace/Cargo.toml
scripts/publish.sh

Some crates had version already updated, some didn't. This updates the missing ones.

chore: Prepare release to pickup 0.29

---

Cargo.toml
deny.toml
opentelemetry-instrumentation-actix-web/CHANGELOG.md
opentelemetry-instrumentation-actix-web/Cargo.toml
opentelemetry-instrumentation-actix-web/README.md
opentelemetry-instrumentation-actix-web/examples/client.rs
opentelemetry-instrumentation-actix-web/examples/server.rs
opentelemetry-instrumentation-actix-web/src/lib.rs
opentelemetry-instrumentation-actix-web/src/middleware/metrics.rs

- removed Prometheus middleware in favour of leveraging OTLP with Prometheus
- I didn't plan on it, but now the crate only depends on `opentelemetry` + `opentelemetry-semantic-conventions` from the OTel family

refactor: remove Prometheus related dependencies from actix instrumentation

---

opentelemetry-resource-detectors/CHANGELOG.md
opentelemetry-resource-detectors/build.rs
opentelemetry-resource-detectors/src/process.rs

Fixes #
Added `process.runtime.name`/`process.runtime.version`/`process.runtime.description`. I'm not sure if these two fields are necessary — feel free to close the PR if they aren't.
<br class="Apple-interchange-newline">[process.runtime.name](https://opentelemetry.io/docs/specs/semconv/attributes-registry/process/)

feat: detect process.runtime.name and process.runtime.version

---

opentelemetry-etw-logs/CHANGELOG.md
opentelemetry-etw-logs/Cargo.toml
opentelemetry-etw-logs/build.rs
opentelemetry-etw-metrics/CHANGELOG.md
opentelemetry-etw-metrics/Cargo.toml

And so, get rid of build.rs, added to fix the build for Rust 1.87.0

fix: [ETW exporter] Bump tracelogging crate to 1.2.4

---

opentelemetry-exporter-geneva/geneva-uploader/Cargo.toml

- this is a temporary fix. I'll first have to fix the problem in the `lz4_flex` crate and hopefully the `0.11.4` will get yanked.

chore: upperbound lz4_flex dependency to fix MSRV check

---

opentelemetry-exporter-geneva/geneva-uploader/Cargo.toml

- a new version of `lz4_flex` was released and the old one was yanked, which makes the upperbound unneeded now (PSeitz/lz4_flex#187)

chore: remove upperbound of lz4_flex dependency

---

opentelemetry-exporter-geneva/geneva-uploader/Cargo.toml
opentelemetry-exporter-geneva/geneva-uploader/src/client.rs
opentelemetry-exporter-geneva/opentelemetry-exporter-geneva/examples/basic.rs
stress/src/geneva_exporter.rs

Towards 4th point of #306.
Enhanced GenevaClient to support concurrent uploads with configurable parallelism, improving throughput for bulk log ingestion.
- Added `max_concurrent_uploads` configuration option to `GenevaClientConfig`
- Modified `upload_logs()` to use `buffer_unordered` for concurrent upload processing
- Moved LZ4 compression into async tasks to enable concurrent compression
- Defaults to number of CPU cores if `max_concurrent_uploads` is not specified
- Enhanced error messages to include event names for better debugging

feat: [Geneva Exporter] Add concurrent uploads to GenevaClient with configurable parallelism

---

opentelemetry-exporter-geneva/geneva-uploader/src/client.rs
opentelemetry-exporter-geneva/geneva-uploader/src/ingestion_service/mod.rs
opentelemetry-exporter-geneva/geneva-uploader/src/ingestion_service/uploader.rs

Replace hardcoded event versions with config-driven versions in Geneva uploader. The `event_version` parameter in URL generation now comes from `config_major_version` and is formatted as `Ver{major_version}v0`.

fix: [Geneva Exporter] Use config version for event_version in payload upload URL generation

---

opentelemetry-exporter-geneva/geneva-uploader/Cargo.toml
opentelemetry-exporter-geneva/geneva-uploader/src/client.rs
opentelemetry-exporter-geneva/geneva-uploader/src/payload_encoder/otlp_encoder.rs
opentelemetry-exporter-geneva/opentelemetry-exporter-geneva/Cargo.toml
opentelemetry-exporter-geneva/opentelemetry-exporter-geneva/examples/trace_basic.rs
opentelemetry-exporter-geneva/opentelemetry-exporter-geneva/src/lib.rs
opentelemetry-exporter-geneva/opentelemetry-exporter-geneva/src/trace/exporter.rs
opentelemetry-exporter-geneva/opentelemetry-exporter-geneva/src/trace/mod.rs

Adds OpenTelemetry span upload functionality to the Geneva exporter, enabling trace data ingestion alongside existing log support.
__Key Changes:__
- __geneva-uploader__: Added span encoding with Bond format, single payload approach using "Span" event name for routing
- __opentelemetry-exporter-geneva__: New `GenevaTraceExporter` implementing `SpanExporter` trait with concurrent upload support
- __Dependencies__: Added "trace" feature to opentelemetry-proto for OTLP span data structures
- __Example__: Added `trace_basic.rs` demonstrating span creation and export with SimpleSpanProcessor
- JSON serialization for span links (C# compatibility)

feat: [Geneva Exporter] Add span upload support to Geneva exporter

---

stress/src/geneva_exporter.rs

Update stress test configuration
- Modified to use current timestamps for event time instead of fixed timestamps, simplifying backend queries by eliminating the need to query for specific historical times
- Changed event name to "Log" to reflect the most common usage scenario

fix: Geneva Uploader - update stress test to use current timestamp for events.

---

opentelemetry-exporter-geneva/geneva-uploader/src/payload_encoder/otlp_encoder.rs

- Remove unnecessary string allocation for HashMap lookups
- Use `if let Some()` instead of `unwrap()` to be safe

fix: [Geneva Uploader] Micro optimizations
