opentelemetry-user-events-metrics/CHANGELOG.md
opentelemetry-user-events-metrics/README.md

Prepare release of user-events-metrics exporter

---

opentelemetry-user-events-metrics/Cargo.toml

Update version for user-events-metrics

---

opentelemetry-aws/CHANGELOG.md

Fixes #
Update changelog position for XrayIdGenerator addition

Update changelog position for XrayIdGenerator addition

---

opentelemetry-aws/CHANGELOG.md
opentelemetry-aws/Cargo.toml
opentelemetry-contrib/CHANGELOG.md
opentelemetry-contrib/Cargo.toml
opentelemetry-datadog/CHANGELOG.md
opentelemetry-datadog/Cargo.toml
opentelemetry-stackdriver/CHANGELOG.md
opentelemetry-user-events-logs/CHANGELOG.md
opentelemetry-user-events-logs/Cargo.toml
opentelemetry-zpages/CHANGELOG.md
opentelemetry-zpages/Cargo.toml

* Update CHANGELOGs
* Bump versions in Cargo.toml

Prepare contrib crates for opentelemetry 0.22.0

---

opentelemetry-aws/CHANGELOG.md
opentelemetry-aws/Cargo.toml
opentelemetry-aws/src/trace/mod.rs
scripts/test.sh

Update changelogs to match existing parlance.
This should allow us to release the next version of opentelemetry-aws.
Fixes #

fix(opentelemetry-aws): Add feature gating to features needing trace.

---

opentelemetry-aws/src/trace/xray_propagator.rs

Remove link to nonexistent example from aws

---

LICENSE
opentelemetry-aws/LICENSE
opentelemetry-contrib/LICENSE
opentelemetry-datadog/LICENSE
opentelemetry-dynatrace/LICENSE
opentelemetry-etw-metrics/LICENSE
opentelemetry-resource-detectors/LICENSE
opentelemetry-zpages/LICENSE

See https://github.com/open-telemetry/community/issues/2056 for background

fix: revert modifications to Apache license

---

.github/workflows/ci.yml
Cargo.toml
opentelemetry-aws/CHANGELOG.md
opentelemetry-contrib/CHANGELOG.md
opentelemetry-contrib/src/trace/exporter/jaeger_json.rs
opentelemetry-etw-logs/CHANGELOG.md
opentelemetry-etw-logs/src/logs/exporter.rs
opentelemetry-etw-logs/src/logs/reentrant_logprocessor.rs
opentelemetry-etw-metrics/CHANGELOG.md
opentelemetry-resource-detectors/CHANGELOG.md
opentelemetry-user-events-logs/CHANGELOG.md
opentelemetry-user-events-logs/Cargo.toml
opentelemetry-user-events-logs/src/logs/exporter.rs
opentelemetry-user-events-logs/src/logs/reentrant_logprocessor.rs
opentelemetry-user-events-metrics/CHANGELOG.md
opentelemetry-user-events-metrics/Cargo.toml

Update to otel-rust v0.23

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

Fix main readme to be consistent with main repo

---

opentelemetry-stackdriver/README.md
opentelemetry-stackdriver/tests/generate.rs

Need to unblock CI, so ignoring the test.

Ignore unstable test

---

Cargo.toml
opentelemetry-etw-logs/src/logs/exporter.rs
opentelemetry-resource-detectors/src/host.rs
opentelemetry-resource-detectors/src/os.rs
opentelemetry-resource-detectors/src/process.rs
opentelemetry-user-events-metrics/src/exporter/mod.rs

opentelemetry 0.26

---

opentelemetry-user-events-metrics/CHANGELOG.md
opentelemetry-user-events-metrics/Cargo.toml
opentelemetry-user-events-metrics/src/exporter/mod.rs

Fixes #124
decoded user_events output from example:
-  before PR : https://hastebin.com/share/oqabohituw.yaml
-  after PR: https://hastebin.com/share/evebojobas.yaml

[User_events metrics exporter] Single Metric point per user_event write.

---

stress/Cargo.toml
stress/src/etw_logs.rs

Add stress test to etw exporter

---

opentelemetry-user-events-logs/CHANGELOG.md
opentelemetry-user-events-logs/examples/basic-logs.rs
opentelemetry-user-events-logs/src/logs/exporter.rs

Fix silently failing when EventSet not found.
Include error code from writing to tracepoint in error message.

UserEvent LogExporter - minor bug fix, improved logging

---

opentelemetry-etw-metrics/Cargo.toml

https://github.com/open-telemetry/opentelemetry-rust-contrib/pull/179 Missed here!

Etwmetric exporter - bump version

---

opentelemetry-user-events-logs/CHANGELOG.md
opentelemetry-user-events-logs/Cargo.toml

UserEvent LogExporter Release

---

opentelemetry-user-events-logs/src/logs/exporter.rs

[user-events log exporter] Fix version and payload type

---

.github/workflows/ci.yml

Hitting rate limit without token!

Use auth token for protoc

---

opentelemetry-user-events-logs/Cargo.toml
opentelemetry-user-events-logs/src/lib.rs
opentelemetry-user-events-logs/src/logs/exporter.rs

Might not work in CI, so can disable and run manually only.

UserEvents - Integration Test

---

.github/workflows/pr_naming.yml
CONTRIBUTING.md

- identical to open-telemetry/opentelemetry-rust#2698

ci: add PR title check

---

opentelemetry-stackdriver/CHANGELOG.md
opentelemetry-stackdriver/proto/google/api/annotations.proto
opentelemetry-stackdriver/proto/google/api/client.proto
opentelemetry-stackdriver/proto/google/api/field_behavior.proto
opentelemetry-stackdriver/proto/google/api/http.proto
opentelemetry-stackdriver/proto/google/api/label.proto
opentelemetry-stackdriver/proto/google/api/launch_stage.proto
opentelemetry-stackdriver/proto/google/api/monitored_resource.proto
opentelemetry-stackdriver/proto/google/api/resource.proto
opentelemetry-stackdriver/proto/google/devtools/cloudtrace/v2/trace.proto
opentelemetry-stackdriver/proto/google/devtools/cloudtrace/v2/tracing.proto
opentelemetry-stackdriver/proto/google/logging/type/http_request.proto
opentelemetry-stackdriver/proto/google/logging/type/log_severity.proto
opentelemetry-stackdriver/proto/google/logging/v2/log_entry.proto
opentelemetry-stackdriver/proto/google/logging/v2/logging.proto
opentelemetry-stackdriver/proto/google/logging/v2/logging_config.proto
opentelemetry-stackdriver/proto/google/rpc/status.proto
opentelemetry-stackdriver/src/proto/api.rs

- CI test failed in my other PR and I didn't want to mix the changes together

feat: update gRPC schemas for Stackdriver

---

Cargo.toml
examples/traceresponse/src/client.rs
examples/traceresponse/src/server.rs
opentelemetry-aws/Cargo.toml
opentelemetry-contrib/CHANGELOG.md
opentelemetry-contrib/Cargo.toml
opentelemetry-contrib/benches/new_span.rs
opentelemetry-contrib/src/trace/exporter/jaeger_json.rs
opentelemetry-datadog/Cargo.toml
opentelemetry-etw-logs/CHANGELOG.md
opentelemetry-etw-logs/src/logs/exporter.rs
opentelemetry-etw-logs/src/logs/reentrant_logprocessor.rs
opentelemetry-etw-metrics/CHANGELOG.md
opentelemetry-etw-metrics/Cargo.toml
opentelemetry-etw-metrics/src/exporter/mod.rs
opentelemetry-resource-detectors/CHANGELOG.md
opentelemetry-stackdriver/Cargo.toml
opentelemetry-user-events-logs/CHANGELOG.md
opentelemetry-user-events-logs/src/logs/exporter.rs
opentelemetry-user-events-logs/src/logs/mod.rs
opentelemetry-user-events-logs/src/logs/reentrant_logprocessor.rs
opentelemetry-user-events-metrics/CHANGELOG.md
opentelemetry-user-events-metrics/Cargo.toml
opentelemetry-user-events-metrics/src/exporter/mod.rs
opentelemetry-user-events-trace/Cargo.toml
opentelemetry-user-events-trace/src/trace/exporter.rs
opentelemetry-user-events-trace/src/trace/mod.rs
opentelemetry-user-events-trace/src/trace/reentrant_spanprocessor.rs
opentelemetry-zpages/CHANGELOG.md
scripts/lint.sh

Not all crates updates, need to find owners for them.

feat: Update upstream dependencies to 0.29 for most crates

---

opentelemetry-etw-logs/CHANGELOG.md
opentelemetry-etw-logs/Cargo.toml
opentelemetry-etw-logs/src/logs/exporter/mod.rs
opentelemetry-etw-logs/src/logs/exporter/part_a.rs
opentelemetry-etw-logs/src/logs/with_etw_exporter.rs

feat: ETW exporter - add support for serializing traceid and spanid 

---

opentelemetry-etw-logs/Cargo.toml
opentelemetry-user-events-logs/src/logs/exporter.rs

@lalitb @utpilla Please review.

chore: Nit comments for following up in etw and userevent exproters

---

opentelemetry-datadog/CHANGELOG.md
opentelemetry-datadog/Cargo.toml
opentelemetry-datadog/benches/datadog_exporter.rs
opentelemetry-datadog/examples/agent_sampling.rs
opentelemetry-datadog/src/exporter/mod.rs
opentelemetry-datadog/src/exporter/model/mod.rs
opentelemetry-datadog/src/lib.rs

chore: update Datadog to OTel 0.29

---

opentelemetry-user-events-logs/CHANGELOG.md
opentelemetry-user-events-logs/src/lib.rs
opentelemetry-user-events-logs/src/logs/exporter.rs
opentelemetry-user-events-logs/src/logs/reentrant_logprocessor.rs

Only "service.name" and "service.instance.id" are mapped.

feat: user-events logs add Resource support

---

opentelemetry-user-events-logs/src/logs/exporter.rs

fix: use severityNumber as i16

---

scripts/test.sh

- this makes it similar to the setup in the main repo
- I also removed all the duplicated tests, which ran the same tests as the first command again

ci: simplify test script

---

opentelemetry-etw-logs/README.md
opentelemetry-etw-logs/src/logs/exporter/mod.rs
opentelemetry-etw-logs/src/logs/exporter/part_a.rs
opentelemetry-user-events-logs/Cargo.toml
opentelemetry-user-events-logs/README.md

chore: nit todo comments to etw log exporter

---

README.md

docs: Add openssf scorecard badge

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/fossa.yml
.github/workflows/ossf-scorecard.yml
.github/workflows/pr_naming.yml

- Add CodeQL workflow
- Update workflow permissions

ci: Add CodeQL workflow

---

opentelemetry-resource-detectors/src/k8s.rs

feat: 🎸 add node name for k8s

---

opentelemetry-user-events-logs/CHANGELOG.md
opentelemetry-user-events-logs/src/lib.rs
opentelemetry-user-events-logs/src/logs/exporter.rs

feat: [Logs user_events exporter] default event_name to log, and flatten ext_dt, ext_cloud

---

scripts/patch_dependencies.sh

chore: patch actix-web to 4.10.2 for MSRV build

---

opentelemetry-user-events-logs/src/lib.rs

Follow up to https://github.com/open-telemetry/opentelemetry-rust-contrib/pull/253

fix: user-events logs - test fix

---

opentelemetry-etw-logs/Cargo.toml

Fixes #
Removed unused deps. Organized them lexicographically. Format toml file.

refactor: opentelemetry_etw_logs dependencies

---

opentelemetry-aws/src/trace/id_generator.rs
opentelemetry-aws/src/trace/xray_propagator.rs
opentelemetry-contrib/src/trace/exporter/jaeger_json.rs
opentelemetry-contrib/src/trace/propagator/trace_context_response.rs
opentelemetry-datadog/src/exporter/intern.rs
opentelemetry-datadog/src/exporter/mod.rs
opentelemetry-etw-logs/src/exporter/mod.rs
opentelemetry-etw-metrics/examples/basic.rs
opentelemetry-exporter-geneva/geneva-uploader/src/config_service/client.rs
opentelemetry-exporter-geneva/geneva-uploader/src/config_service/mod.rs
opentelemetry-exporter-geneva/geneva-uploader/src/ingestion_service/mod.rs
opentelemetry-exporter-geneva/geneva-uploader/src/ingestion_service/uploader.rs
opentelemetry-exporter-geneva/geneva-uploader/src/payload_encoder/bond_encoder.rs
opentelemetry-instrumentation-actix-web/examples/client.rs
opentelemetry-instrumentation-actix-web/src/client.rs
opentelemetry-instrumentation-actix-web/src/middleware/trace.rs
opentelemetry-instrumentation-actix-web/src/util.rs
opentelemetry-resource-detectors/build.rs
opentelemetry-stackdriver/src/lib.rs
opentelemetry-user-events-logs/examples/basic-logs.rs
opentelemetry-user-events-logs/src/lib.rs
opentelemetry-user-events-logs/src/logs/exporter.rs
opentelemetry-user-events-logs/src/logs/processor.rs
opentelemetry-user-events-metrics/src/exporter/mod.rs
opentelemetry-user-events-metrics/src/lib.rs
opentelemetry-user-events-trace/examples/basic-trace.rs
opentelemetry-user-events-trace/src/trace/exporter.rs
stress/src/throughput.rs

Fixes #328
changes pulled from #329.

fix: lint failing with rustc 1.88

---

.github/workflows/ci.yml

Fixes #331 
picked from copilot PR: #332

fix: CI llmv-cov coverage

---

opentelemetry-user-events-trace/CHANGELOG.md
opentelemetry-user-events-trace/Cargo.toml
opentelemetry-user-events-trace/examples/basic-trace.rs
opentelemetry-user-events-trace/src/trace/exporter.rs
opentelemetry-user-events-trace/src/trace/reentrant_spanprocessor.rs

Manual testing still. Will be adding integration tests subsequently.

feat: UserEvents TraceExporter - add support for Resource, nit fixes

---

opentelemetry-exporter-geneva/geneva-uploader-ffi/Cargo.toml
opentelemetry-exporter-geneva/geneva-uploader-ffi/examples/otlp_builder/Cargo.toml
opentelemetry-exporter-geneva/geneva-uploader/Cargo.toml
opentelemetry-exporter-geneva/opentelemetry-exporter-geneva/Cargo.toml

- Add description, homepage, repository, keywords attributes
- Follow format from opentelemetry-user-events-logs example
- Updated all 4 Cargo.toml files in opentelemetry-exporter-geneva
Fixes #

feat: [Geneva Exporter] Add missing package attributes to Geneva exporter crates
